"""Add emergency, resolved flag, and other updates to models

Revision ID: 57d64d2fa906
Revises: 
Create Date: 2025-05-26 22:45:15.773987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d64d2fa906'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.drop_column('emergency')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('resolved')

    # ### end Alembic commands ###
